
// action types
export const FULL_URL_CHANGED = 'FULL_URL_CHANGED';
export type FULL_URL_CHANGED = typeof FULL_URL_CHANGED;

export const MODAL_ACCEPT_PRESSED = 'MODAL_ACCEPT_PRESSED';
export type MODAL_ACCEPT_PRESSED = typeof MODAL_ACCEPT_PRESSED;

export const MODAL_CANCEL_PRESSED = 'MODAL_CANCEL_PRESSED';
export type MODAL_CANCEL_PRESSED = typeof MODAL_CANCEL_PRESSED;

export const ON_CUSTOM_HASH_CHECK_IS_RESOLVED = 'ON_CUSTOM_HASH_CHECK_IS_RESOLVED';
export type ON_CUSTOM_HASH_CHECK_IS_RESOLVED = typeof ON_CUSTOM_HASH_CHECK_IS_RESOLVED;

export const ON_HASH_INPUT_CHANGE = 'ON_HASH_INPUT_CHANGE';
export type ON_HASH_INPUT_CHANGE = typeof ON_HASH_INPUT_CHANGE;

export const ON_SAVED_HASH_TO_ETHEREUM = 'ON_SAVED_HASH_TO_ETHEREUM';
export type ON_SAVED_HASH_TO_ETHEREUM = typeof ON_SAVED_HASH_TO_ETHEREUM;

export const ON_SENDING_HASH_TO_ETHEREUM = 'ON_SENDING_HASH_TO_ETHEREUM';
export type ON_SENDING_HASH_TO_ETHEREUM = typeof ON_SENDING_HASH_TO_ETHEREUM;

export const SET_BACKING_STORE = 'SET_BACKING_STORE';
export type SET_BACKING_STORE = typeof SET_BACKING_STORE;

export const SET_OPTIONS_VISIBILITY = 'SET_OPTIONS_VISIBILITY';
export type SET_OPTIONS_VISIBILITY = typeof SET_OPTIONS_VISIBILITY;

export const SHOW_METAMASK_DIALOG = 'SHOW_METAMASK_DIALOG';
export type SHOW_METAMASK_DIALOG = typeof SHOW_METAMASK_DIALOG;

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export type UPDATE_MESSAGE = typeof UPDATE_MESSAGE;

export const UPDATE_WEB3_STATE = 'UPDATE_WEB3_STATE';
export type UPDATE_WEB3_STATE = typeof UPDATE_WEB3_STATE;
