
// action types
export const FULL_URL_CHANGED = 'FULL_URL_CHANGED';
export type FULL_URL_CHANGED = typeof FULL_URL_CHANGED;

export const SUBMIT_BUTTON_PRESSED = 'SUBMIT_BUTTON_PRESSED';
export const HASH_INPUT_CHANGED = 'HASH_INPUT_CHANGED';

export const MODAL_ACCEPT_PRESSED = 'MODAL_ACCEPT_PRESSED';
export type MODAL_ACCEPT_PRESSED = typeof MODAL_ACCEPT_PRESSED;

export const MODAL_CANCEL_PRESSED = 'MODAL_CANCEL_PRESSED';
export type MODAL_CANCEL_PRESSED = typeof MODAL_CANCEL_PRESSED;

export const SHOW_METAMASK_DIALOG = 'SHOW_METAMASK_DIALOG';
export type SHOW_METAMASK_DIALOG = typeof SHOW_METAMASK_DIALOG;
// TODO savil. add more
